# Generated by Django 6.0.5 on 2026-06-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_feestructure_feepayment_feeinstallment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='due_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='exam_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='hostel_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='late_fee_penalty',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='library_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='other_fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='transport_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='tuition_fee',
            field=models.IntegerField(default=0),
        ),
    ]
